### ISSUE TITLE
Create the models for `listings` app

### ISSUE THREAD

**Issue by eyobofficial** [ZedeLab/WhatsUpAddis-BE#5]
## Task
- [ ] Add models to the `listings` app as per the tables given below
- [ ] Create the necessary migration files
- [ ] Register the models to the admin site.

## Model 1: Category
For managing the different business categories and types.

|Field                   |  Data types   |
|----------------------|-------------------|
|name                 | CharField      |
|description         | TextField       |
|wallpaper           | ImageField    |

## Model 2: Business
For managing the different business instances.

|Field                   |  Data types   |
|----------------------|-------------------|
|name                 | CharField      |
|description         | TextField       |
|latitude               | FloatField      |
|longitude            | FloatField      |
|wallpaper           | ImageField    |
|email                  | EmailField     |
|phone_number   | CharField      |
| facebook            | URLField      |
| instagram          | URLField       |
| twitter                | URLField       |
| start_date          | DateField       | 
| end_date           | DateField      |
| opening_hour    | DateField      |
| closing_hour      | DateField      |
| menu                 | ImageField   |
| is_premium        | BooleanField|
| is_featured         | BooleanField|
| is_approved      | BooleanField |
| created_at         | DateTimeField|
|updated_at         | DateTimeField|

**Notes**:
* The `menu` field is meant for business instances with `food` category.
* The `start_date` and `end_date` fields are meant for business instances with `event` category.
